# Generated by Django 5.1.5 on 2026-03-04 09:11

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcement_types', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Announcement title.', max_length=255)),
                ('description', models.TextField(help_text='Announcement body/description.')),
                ('image', models.ImageField(blank=True, help_text='Optional image attachment.', null=True, upload_to='announcements/images/%Y/%m/', validators=[core.validators.validate_image_file])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', help_text='Announcement visibility status.', max_length=10)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Manager who created the announcement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Department the announcement belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='departments.department')),
                ('type', models.ForeignKey(help_text='Category/type of the announcement.', on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='announcement_types.announcementtype')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'is_deleted', '-created_at'], name='idx_active_announcements'), models.Index(fields=['department', 'status'], name='idx_dept_status'), models.Index(fields=['type', 'status'], name='idx_type_status')],
            },
        ),
    ]
