# Generated by Django 5.1.5 on 2026-03-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Announcement type name (e.g., General, Urgent, Event).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the announcement type.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the announcement type is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement Type',
                'verbose_name_plural': 'Announcement Types',
                'db_table': 'announcement_types',
                'ordering': ['name'],
            },
        ),
    ]
